name: Swift

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - ubuntu-16.04

          - windows-latest

          - macos-latest
          # - macos-11.0  # add this when it's supported

    steps:
      - uses: actions/checkout@v2

      - name: Install Swift
        if: ${{ os == 'windows-latest' }}
        run: echo 'We should install Swift here.'

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
